#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend therihun.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
	server 204572-web-01 52.7.61.238:80 check
        server 204572-web-02 100.25.204.201:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
