#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

    echo "
        listen load_balancer
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 204572-web-01 52.7.61.238:80 check
        server 204572-web-02 100.25.204.201:80 check

    " >> /etc/haproxy/haproxy.cfg

service haproxy start
